### ISSUE TITLE
[Bug]: undefined method `organization_api_key=' for an instance of OneSignal::Configuration

### ISSUE THREAD

**Issue by cardmagic** [OneSignal/onesignal-ruby-api#54]
### What happened?

The documentation says:

```
# Setup authorization
OneSignal.configure do |config|
  # Configure Bearer authorization: organization_api_key
  config.organization_api_key = 'ORGANIZATION_API_KEY' # Organization key is only required for creating new apps and other top-level endpoints
  # Configure Bearer authorization: rest_api_key
  config.rest_api_key = 'REST_API_KEY' # App REST API key required for most endpoints
end
```

But this code doesn't work in the onesignal v2.2.1 gem

### Steps to reproduce?

```Markdown
Open `rails c` and run:


irb(main):001* OneSignal.configure do |config|
irb(main):002*   # Configure Bearer authorization: organization_api_key
irb(main):003*   config.organization_api_key = 'ORGANIZATION_API_KEY' # Organization key is only required for creating new apps and other top-level endpoints
irb(main):004*   # Configure Bearer authorization: rest_api_key
irb(main):005*   config.rest_api_key = 'REST_API_KEY' # App REST API key required for most endpoints
irb(main):006> end
irb(main):007> 
(irb):3:in `block in <main>': undefined method `organization_api_key=' for an instance of OneSignal::Configuration (NoMethodError)

  config.organization_api_key = 'ORGANIZATION_API_KEY' # Organization key is only required for creating new apps and other top-level endpoints
        ^^^^^^^^^^^^^^^^^^^^^^^
	from (irb):1:in `<main>'
```

### What did you expect to happen?

I expect the documentation to give code that works.

### Relevant log output

```Shell
(irb):3:in `block in <main>': undefined method `organization_api_key=' for an instance of OneSignal::Configuration (NoMethodError)

  config.organization_api_key = 'ORGANIZATION_API_KEY' # Organization key is only required for creating new apps and other top-level endpoints
        ^^^^^^^^^^^^^^^^^^^^^^^
	from (irb):1:in `<main>'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sherwinski** [comment]
Hi @cardmagic,

If you are using v2 of the gem then you will want to use `user_key` instead. This is because we chose to rename the auth config key during the most recent major version release for better clarity.

Here's a link to the gem's [v2 docs](https://github.com/OneSignal/onesignal-ruby-api/tree/player-model-main?tab=readme-ov-file#getting-started) -- please let us know if you have any other questions or run into any issues.

**Comment by cardmagic** [comment]
I see, thank you. You may want to update the README to specify v1 vs v2 config, and since v2 is the default that comes when you `gem install onesignal` you probably want to make v2 docs default too

**Comment by sherwinski** [comment]
Good point, thanks for calling that out.
